### ISSUE TITLE
[Bug] Address warnings during the Docker build

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-explorer#109]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
While the container image is building, several errors appear (highlighted in red on my terminal) concerning various items being out of date. There are also other messages that imply things could be wrong. As much as possible the goal should be to have a completely clean build with zero warnings. Any warnings that cannot be removed should be documented along with reasons that justify not fixing them.

**Comment by krlawrence** [comment]
Example of confusion caused by just this issue: #117

**Comment by joywa** [comment]
This is now closed in the latest PR #118. Thank you for reporting @krlawrence !
