### ISSUE TITLE
[Feature Request] Distribute Graph Explorer static website as a React library (e.g. via NPM)

### ISSUE THREAD

**Issue by JeeZeh** [aws/graph-explorer#110]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Is your feature request related to a problem? Please describe.**
It is not currently possible (?) to host the Graph Explorer website/UI as part of another static website. For folks who already have a deployment of some sort of static website, it would be preferred to re-use the existing deployment, allowing the Graph Explorer to be accessed via some route of their application. 

For example, in our setup we already have infrastructure for protecting access to the website, as well as making calls to APIs (that could be used to forward requests to the Neptune). It would be significantly easier for us to use the Graph Explorer if it could be treated as an importable React component/module.

**Describe the solution you'd like**
In an ideal world, the graph explorer would be an NPM module that can be hosted inside any other React application, e.g.

Install the module: `npm i -s @aws/graph-explorer-website`

Add the component to your application, e.g. as route on a different path:
```
import { GraphExplorer } from "@aws/graph-explorer-website"

<Routes> 
     <Route path="/" element={<MyApp/>}/>
     <Route path="/explorer" element={<GraphExplorer config={config} />}/>
</Routes>
```

**Comment by kmcginnes** [comment]
@akashg90 The graph visualization library is already available. We use [Cytoscape](https://cytoscape.org/).

**Comment by kmcginnes** [comment]
Unfortunately, this feature request does not align with our goals for Graph Explorer. The app itself will remain a separate required deployment that you can link to from other apps.

This does not mean we are shutting the door on having reusable components in the future that you might be able to add to other apps.
