### ISSUE TITLE
[Bug] caniuse and browserlist not updating with docker

### ISSUE THREAD

**Issue by davinci07** [aws/graph-explorer#117]
Hello all!

I've been trying to run this graph-explorer and followed the instructions as necessary. However on STEP 8/12 after running `docker build -t graph-explorer .` in the root directory with running to this error:

`
(!) "base" option should end with a slash.
vite v3.2.0 building for production...
transforming...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
`

This is running in an EC2 instance with AWS Linux (CentOS) with about 30 GB of memory and it should connect to Neptune that is in the same VPC and subnet. I have tried it on ubuntu on May 25 2023 and it ran without issues. Do to company policy, I would need to use AWS Linux instead of ubuntu. 

Things I have tried:
- upgrading nodejs
- updating browserlist and caniuse packages through npm
- using yarn to upgrade 
- upgrading yum 

It seems like an issue in the docker container. What could work in this situation? Should I update something in the dockerfile?

**Comment by joywa** [comment]
@davinci07 this is now closed with PR #118 , thank you for reporting!
