### ISSUE TITLE
[Bug] Sychronization fails for large RDF dataset

### ISSUE THREAD

**Issue by michaelnchin** [aws/graph-explorer#133]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**

A customer is attempting to synchronize Explorer to a large RDF graph loaded into a Neptune cluster with Summary API support. The dataset, [DBLP](https://dblp.org/rdf/), in RDFXML format, has a size of 24GB, and contains ~364m triples accounting for duplicates.

On synchronization, we can confirm that this is not due to connectivity issues with the Neptune cluster, as the initial Summary API request succeeds. However, when the remaining SPARQL HTTP requests are executed to fetch the remaining schema information, all of them error out with a `504 Gateway Timeout` due to a base limit of 60 seconds per fetch request.

If we execute some of these same SPARQL queries through graph-notebook, they are able to succeed. For example, the [predicatesByClass](https://github.com/aws/graph-explorer/blob/b371145b39ddef878ab349b5dce18e271d97524a/packages/graph-explorer/src/connector/sparql/templates/predicatesByClassTemplate.ts#L4) query completes in ~86 seconds - this does not exceed the base Neptune query timeout of 2 minutes, but is too high for Explorer.

![Screen Shot 2023-07-12 at 11 38 25 PM](https://github.com/aws/graph-explorer/assets/10456376/ec6cf5e9-c5f8-4923-8360-f4243d170619)

**Fixes tried**

I've looked into possible solutions involving hard-coding an increased timeout limit into the request. The fetch API, as used in the base [_requestAndCache method](https://github.com/aws/graph-explorer/blob/b371145b39ddef878ab349b5dce18e271d97524a/packages/graph-explorer/src/connector/AbstractConnector.ts#L307) in AbstractConnector, seems to accept a custom timeout through its `signal` init setting when it is defined as [AbortSignal.timeout([time_in_ms])](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static). 

At the upper level, the fetchSchema method in SPARQLConnector [defines the init settings](https://github.com/aws/graph-explorer/blob/b371145b39ddef878ab349b5dce18e271d97524a/packages/graph-explorer/src/connector/sparql/SPARQLConnector.ts#L33) to be passed down to the base fetch call. I tried modifying this line to also pass in the custom signal setting with timeout at 500k ms:
```
 const ops = { ...options, abortSignal: AbortSignal.timeout(500000), disableCache: true };
```

Unfortunately, this did not have an effect (or I implemented it incorrectly), as the schema query requests still timed out at exactly 60 seconds.

 - OS: Mac OS X
 - Browser: Google Chrome 114.x / Firefox 102.x
 - Graph Explorer Version: 1.2.0 / latest mainline build
 - Graph Database & Version: Amazon Neptune 1.2.1.0

**To Reproduce**

1. Bulk load the DBLP RDF dataset (dblp.rdf.gz [here](dblp.rdf.gz)) into your Neptune cluster.
2. Attempt to initiate sync to Neptune on SPARQL graph type.
3. Wait ~60 seconds, observe sync error.
4. Open browser console and see 504 errors.

**Expected behavior**

Connection sync should complete on large RDF datasets. We should increase the timeout to be much higher, or give the user an option to set a custom query timeout limit in the Connections UI.

**If applicable, add screenshots to help explain your problem.**

In Firefox:

<img width="1765" alt="sync_timeout_firefox" src="https://github.com/aws/graph-explorer/assets/10456376/295528d0-7d89-4b64-957b-03d61052af88">

In Chrome:

![Screen Shot 2023-07-12 at 9 13 08 PM](https://github.com/aws/graph-explorer/assets/10456376/6e6b5b33-31ba-4533-9822-d630fe2dbf41)

**Comment by miguelsmuller** [comment]
I seem to be having the same problem here.

I have 2 clusters on AWS Neptune.
Environment 1 has approximately 64GB and contains 120,302,148 triples.
Environment 2 has approximately 70GB and contains 145,403,562 triples.
I got these sizes in GB from the last snapshot.

The AWS Graph Explorer works, syncing correctly to Environment 1, but the synchronization fails for Environment 2.
There are several successful requests, but then it fails!

Could this be related to your issue @michaelnchin ?

I'd like to help with this issue, but I'm not sure how I can contribute.

![Screenshot 2023-07-27 at 17 45 24](https://github.com/aws/graph-explorer/assets/4589909/0d64d67d-cadc-4c01-ab16-b37b2c7cf7de)

**Comment by xiazcy** [comment]
Resolved in https://github.com/aws/graph-explorer/pull/199.
