### ISSUE TITLE
[Bug] Deleting my graph then clearing the Graph Explorer cache still results in non-zero node and edge count

### ISSUE THREAD

**Issue by kwokmeli** [aws/graph-explorer#147]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
After deleting my graph and clearing the Graph Explorer cache, the main connection pane in Graph Explorer says there's no nodes (correct) but the node and edge count is still non-zero. I would expect the node and edge count to be zero for both.

 - OS: Amazon Linux 2023
 - Browser: Google Chrome Version 115.0.5790.114
 - Graph Explorer Version: 1.2.0
 - Graph Database & Version: Neptune 1.2.1.0.R3

**To Reproduce**
1. Connect Graph Explorer to a graph with a non-zero amount of nodes and edges. Synchronize it.
2. Delete everything in your graph.
3. Set the connection cache time in Graph Explorer to zero and/or uncheck "Enable Cache".
4. Synchronize the connection again.

**Expected behavior**
I expect the node and edge count to be zero after syncing against an empty graph. Instead, I see the following:
<img width="568" alt="Screen Shot 2023-08-02 at 9 31 04 AM" src="https://github.com/aws/graph-explorer/assets/14933008/0908fe10-c03a-4abd-ac2e-a4deef4b5243">

**Comment by xiazcy** [comment]
Issue resolved in #209.
