### ISSUE TITLE
[Feature Request] Allow node ID as search option in search bar

### ISSUE THREAD

**Issue by mhavey** [aws/graph-explorer#150]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Graph Explorer Version (and Graph Database and Version used if applicable)**
All

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm frustrated when [...]
This is a blocking issue. The node IDs are meaningful business IDs for many customers. Allow them to perform an EXACT search on just the ID.

**Describe the solution you'd like**
If user wants to find node with ID x, from the search bar in the upper middle, allow them to search the exact ID value for that node type. Currently ID is not offered in the drop down.

**Additional context**
Add any other context or screenshots about the feature request here. Describe any alternatives you've considered.

**Comment by kmcginnes** [comment]
@mhavey Searching by ID specifically is now supported in version 1.6 of Graph Explorer.

Thank you for your great suggestion!
