### ISSUE TITLE
[Bug] Node ID search erroring out

### ISSUE THREAD

**Issue by mhavey** [aws/graph-explorer#153]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
A clear and concise description of what the bug is and the environment/context.
User uses search bar in upper middle to search for a person node by ID (nm0614165). Because ID from the dropdown, the user searches on all properties. The underlying Gremlin that is created is the following:

g.V().hasLabel("person").or(has(id,containing("nm0614165")),has("oscar_nominee",containing("nm0614165")),has("oscar_winner",containing("nm0614165")),has("name",containing("nm0614165"))).range(0,10)

Neptune responds with UnsupportedOperationException

 - OS: [e.g. Amazon Linux 2]
 - Browser: [e.g. Google Chrome] Multiple
 - Graph Explorer Version: [e.g. 1.0.0] main branch as of 7/30
 - Graph Database & Version: [e.g., Amazon Neptune 1.2.0.2] 1.2.x

**To Reproduce**
Steps to reproduce the behavior: see above

**Expected behavior**
There is exactly one node that matches the search criteria. It should be presented.

**Comment by kmcginnes** [comment]
@mhavey Searching by ID specifically is now supported in version 1.6 of Graph Explorer.

Thank you for your great suggestion!
