### ISSUE TITLE
[Bug] Ensure search by ID is excluded when searching on a specific node attribute

### ISSUE THREAD

**Issue by StrongPa55w0rd** [aws/graph-explorer#171]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
A clear and concise description of what the bug is and the environment/context.

 - OS: [e.g. Amazon Linux 2]
 - Browser: [e.g. Google Chrome]
 - Graph Explorer Version: [e.g. 1.0.0]
 - Graph Database & Version: [e.g., Amazon Neptune 1.2.0.2]

**To Reproduce**

**Expected behavior**

**Comment by michaelnchin** [comment]
Closing as a duplicate of #168
