### ISSUE TITLE
Unable to connect using OpenCypher graph type

### ISSUE THREAD

**Issue by ttemple06** [aws/graph-explorer#196]
I have a local gremlin server (3.4.0) running and I am able to get graph-explorer connected to it without issues.
When I edit the connection and switch to "PG (Property Graph) - OpenCypher" graph type, I get an 400 error response, "no gremlin script supplied". I have tried running with nodejs via `npm run serve` as well as with docker, and get the same result. I see that openCypher support was added with #67 and I do not see anything inside that PR which would indicate something different is required other than to change the graph type value inside the Update connection modal. Could someone please tell me what I am missing? TYIA!
![image](https://github.com/aws/graph-explorer/assets/37306883/80d4f806-056a-4fc9-b524-2bb2eaad1c7f)

**Comment by mohitanchlia** [comment]
ANy updates on this? I have the same issue

**Comment by BeyondEvil** [comment]
Try this. Import the connection using JSON, and for `type` set `opencypher` instead of `openCypher` (see difference in case).

That worked for me.

**Comment by kmcginnes** [comment]
@ttemple06 The short answer is that it is not possible.

While it is true that Graph Explorer supports three different query engines (i.e. Gremlin, OpenCypher, and SPARQL) the Gremlin Server you are connecting to only supports the Gremlin query language.

To use Graph Explorer with the OpenCypher query engine you must connect to a database that supports OpenCypher, such as Amazon Neptune.

**Comment by ttemple06** [comment]
@Cole-Greer thanks for your reply! Is that still true even with opencypher plugin on gremlin server?

**Comment by kmcginnes** [comment]
@ttemple06 We aren't familiar with any OpenCypher plugins for Gremlin Server. 

The OpenCypher support in Graph Explorer is designed to use Neptune's OpenCypher HTTP API. If the Gremlin Server plugin you are referring to implements that same API then it should work, otherwise it is unsupported.
