### ISSUE TITLE
[Bug] Invalid Accept header for SPARQL endpoint

### ISSUE THREAD

**Issue by dzieciou** [aws/graph-explorer#229]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
A clear and concise description of what the bug is and the environment/context.

 - OS: Ubuntu 20
 - Browser: Google Chrome
 - Graph Explorer Version: 1.5.0
 - Graph Database & Version: Virtuoso 7.2.0

**To Reproduce**
1. Import the following connection configuration with a public SPARQL endpoint:
   ```json
	{
	  "id": "7dbc341d-68c7-4f60-8880-1e58575b4c6b",
	  "displayLabel": "Bio2Rdf Connection",
	  "connection": {
		"url": "https://bio2rdf.org",
		"queryEngine": "sparql",
		"proxyConnection": false,
		"graphDbUrl": "",
		"awsAuthEnabled": false,
		"awsRegion": "",
		"cacheTimeMs": 600000
	  },
	  "schema": {
		"vertices": [],
		"edges": [],
		"prefixes": []
	  }
	}
    ```
2. Click to synchronize 

Synchronization fails with 
```
Error while fetching schema: Unexpected token '<', "<sparql xm"... is not valid JSON
```

This is because `https://bio2rdf.org/sparql` returns SPARQL query results in XML format, while the client expects JSON format.

**Expected behavior**

Graph-explorer should be able to handle SPARQL endpoints. Please take a look at *Root Cause Analysis* below for details.

**Root Cause Analysis**

The problem happens because the graph-explorer does not specify the expected serialization format for the SPARQL query endpoint. 

Here's the request being sent:

```bash
curl 'https://bio2rdf.org/sparql' \
  -H 'accept: */*' \
  --data-raw 'query=%0A%20%20%20%20SELECT%20%3Fclass%20%20(COUNT(%3Fstart)%20AS%20%3FinstancesCount)%20%7B%0A%20%20%20%20%20%20%3Fstart%20a%20%3Fclass%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Fclass%0A%20%20' \
  --compressed
```
That can be changed by specifying a proper `Accept` HTTP request header. Proper values are:
- `application/sparql-results+json` or
- `application/json`

See [W3C specification for SPARQL Protocol](https://www.w3.org/TR/sparql11-protocol/#conneg): 

> Protocol clients should use HTTP content negotiation [RFC2616] to request response formats that the client can consume. See below for more on potential response formats.

and W3C specification for [SPARQL 1.1 Query Results JSON Format]( https://www.w3.org/TR/sparql11-results-json/#content-type)

Here's a call that returns a response in JSON format.
```bash
curl 'https://bio2rdf.org/sparql' \
-H 'accept: application/json' \
--data-raw 'query=%0A%20%20%20%20SELECT%20%3Fclass%20%20(COUNT(%3Fstart)%20AS%20%3FinstancesCount)%20%7B%0A%20%20%20%20%20%20%3Fstart%20a%20%3Fclass%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Fclass%0A%20%20' \
--compressed
```

After overriding HTTP request headers sent by graph-explorer (via Chrome plugin) I got the right results.

![image](https://github.com/aws/graph-explorer/assets/7452788/06cd1f6f-a377-4cb4-9df7-1b3cf4ddff92)

**Comment by michaelnchin** [comment]
Thanks @dzieciou ! This has been fixed with #230.
