### ISSUE TITLE
Improve search function performance 

### ISSUE THREAD

**Issue by charlesivie** [aws/graph-explorer#237]
The main search feature needs optimisation. make the following improvements:

1. Allow for search by ID, always, by default, as this is not a specified property in PG especially. For RDF, use the default label set.
2. Before the main search is run, execute an exact match search on the search value
3. Only initiate the search when the user has stopped typing
4. Only initiate the search after at least three characters have been entered
5. Default the search to exact match by ID, to avoid the initial search being potentially slow

**SEE BELOW COMMENTS FOR EXTENDED TEST CRITERIA**

**Comment by charlesivie** [comment]
Lets also add this criteria to testing : 
"I want to search only specific edge labels from a node, when i select that specific edge type in the Entities Filter and deselect others and expand on the vertex it doesn't work, instead it loads up all of the edge types.
How can i get all the edges of specific edgeType/label in the view from a node?"

**Comment by kmcginnes** [comment]
> Lets also add this criteria to testing : "I want to search only specific edge labels from a node, when i select that specific edge type in the Entities Filter and deselect others and expand on the vertex it doesn't work, instead it loads up all of the edge types. How can i get all the edges of specific edgeType/label in the view from a node?"

@charlesivie I created a new GitHub issue #249 for this change

**Comment by kmcginnes** [comment]
@charlesivie I think we have covered all the points in this issue. Do you think we can close this issue? 

If something is missed or needs tweaking we can always open another issue.

**Comment by kmcginnes** [comment]
Relavent issue #150
