### ISSUE TITLE
[Bug] Support for Gremlin Server 3.7 is broken

### ISSUE THREAD

**Issue by ARYAN0KUMAR** [aws/graph-explorer#277]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

I was trying to connect graph explorer to gremlin server. I made the changes as per the connections.md docs.
Change `gremlin.tinkergraph.vertexIdManager` and `gremlin.tinkergraph.edgeIdManager` in `/conf/tinkergraph-empty.properties` to support string ids. You can use `ANY`
As soon as i did this my graph was unable to save boolean values. I changed it back to default but then graph explorer wouldn't read it. Also this resulted in my edges not being created. 

gremlin.graph=org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph
gremlin.tinkergraph.vertexIdManager=ANY
gremlin.tinkergraph.edgeIdManager=ANY

in tinkergraph-empty.properties

 - OS: Windows 10
 - Browser: Google Chrome
 - Graph Explorer Version: 1.5.1
 - Graph Database & Version: gremlin server 3.7.0

First I need that changing the default values to ANY should not impact how the graph used to behave originally and save data originally and secondly it should connect to graphexplorer and display everything correctly.

**Comment by kmcginnes** [comment]
@ARYAN0KUMAR Thank you for the bug submission. Would you mind adding a descriptive title to this bug. Something like:

> Support for Gremlin Server 3.7 is broken

**Comment by triggan** [comment]
Related: https://stackoverflow.com/questions/78197550/trying-to-use-aws-graphexplorer-as-a-visualizer-for-local-gremlin-server-does-no
