### ISSUE TITLE
[Bug] Using the air-routes data set the DFW airport does not expand correctly

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-explorer#314]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
Environment: 
- Amazon Neptune version 1.3.1.0
- Graph Explorer V 1.6.0
- Gremlin connection type

With the air routes data set loaded, add the DFW airport to the canvas and expand it so that all 253 connected airports are shown. Once this is done, none of the adjacent airports can be further expanded. If the expanded number of adjacent airports is limited to say 10, things work as expected. There are several areas that can be improved here.

1. Data about the adjacent airports is never correctly fetched. Further exploration is impossible.
2. The Explorer sends 253 HTTP requests in rapid succession to get the information about the adjacent airports. This can result in throttling exceptions. I saw a lot of errors in the browser debug console (network tab).
3. The Gremlin queries being used are very simple of the form `"g.V(\"178\").both().limit(500).dedup().group().by(label).by(count())` . A better scheme might be to fetch data about batches of nodes at a time (maybe 10 or even 50)
4. The "Updating neighbors" pop-up never goes away

![image](https://github.com/aws/graph-explorer/assets/27897072/e5f02c60-56d8-4d92-a6ff-dd16d8c15c46)

**Expected behavior**
You should be able to further expand and explore the graph.

**Comment by kmcginnes** [comment]
- Might be partially related to #324

**Comment by kmcginnes** [comment]
This has been resolved by the work done in

- #432
