### ISSUE TITLE
Connecting to non-neptune TinkerPop db

### ISSUE THREAD

**Issue by yuvallb** [aws/graph-explorer#33]
Trying to connect to a TinkerPop database, I get the error "Synchronization Required
It is necessary to synchronize the connection to be able to work with the database."
Looking into network calls, I see it tries to query g.V().groupCount().by(label)
which is refused with the error message:
Could not find a suitable index to answer graph query and graph scans are disabled

Seems like an index on label is required to run graph-explorer

**Comment by bechbd** [comment]
What TinkerPop database are you running against?

**Comment by yuvallb** [comment]
JanusGraph
It has a specific setting to disable queries that do not use an index

**Comment by krlawrence** [comment]
Are you able to enable full graph scans for the near term? The GraphExplorer does not try to interrogate the back end currently to see what indexes exist. Also, as far as I am aware, JanusGraph does not support indexing a label (or at least it did not used to when I used it more regularly).

**Comment by otnt** [comment]
The same error happened to me as well when connecting to a gremlin server.

**Comment by krlawrence** [comment]
@otnt Which database backend were you using, was it also JanusGraph? Are you still seeing the issue with the latest version of Graph Explorer? @yuvallb were you ever able to get it working with JanusGraph? Just checking for any more information before taking a deeper look at this one. Several fixes and improvements have been made in the meantime that may also help with this issue.

**Comment by krlawrence** [comment]
I was able to reproduce the issue pretty much as described. Using:
1. JanusGraph 0.6.3 running with a Gremlin Server using the WsAndHttpsChannelizer and an in-memory graph. Everything else pretty much defaults.
2. Graph Explorer built to use HTTP rather than HTTPS (just to make connecting easier)
3. The schema of my small test graph was correctly fetched
4. The minute I clicked in the search bar of the Explorer an exception was thrown and the browser window went to just a white background with nothing else.

**Comment by krlawrence** [comment]
Issue #55 is potentially related to this issue. It may not be the root cause but given the ID scheme used by JanusGraph the fix for that issue will also be required before JanusGraph fully works with GraphExplorer.

**Comment by krlawrence** [comment]
I built a version of Graph Explorer using the current PR #60 and was able to get data to display using Janus Graph. Once PR #60 merges, this issue can hopefully be resolved/closed.

**Comment by cubeddu** [comment]
Looks like issue has been resolved. please re-open if it's not the case.
