### ISSUE TITLE
Create a `latest` tag pointed at the most recent stable release

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#333]
Someone with permissions will need to manually push a latest tag that points to the latest stable release `v1.6.0`.

**Comment by michaelnchin** [comment]
`latest`/`sagemaker-latest` tags based off of the [1.6.x](https://github.com/aws/graph-explorer/tree/1.6.x) release branch have been published to ECR: 

https://gallery.ecr.aws/neptune/graph-explorer
