### ISSUE TITLE
[Bug] Newly added edge properties are not reflected by the Explorer

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-explorer#349]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Summary**
If a new property is added to an existing edge, the new property does not get reflected when that edge is displayed in the Explorer.  Having run the query below:
```
g.E('5064').property('my-new-property',123)
```
inside the database the edge now has the following properties
```
g.E('5064').valueMap()

{'my-new-property': 123, 'dist': 708}
```

However, when the edge is displayed on the explorer it only shows the original property in the details panel. 

![image](https://github.com/aws/graph-explorer/assets/27897072/35555e44-c468-4531-b64b-9a4cf1b44c06)

If the browser debugger is used, under the network view, you can see that the Explore does fetch the new property values, but does not then include them in the details view. I also experimented with re-running sync. and nothing seemed to force the Explorer to actually display the new values. It almost feels as if the prior values have somehow been cached.

The image below shows that in the browser debugger the new edge properties were fetched (but not used in the display)

![image](https://github.com/aws/graph-explorer/assets/27897072/2bae005a-1b75-457b-9fbf-32bc33222772)

**Comment by kmcginnes** [comment]
I briefly poked around the code and it looks like it attempts to do the right thing. So something must be broken.
