### ISSUE TITLE
[Feature Request] Prefer HTTP GET over POST

### ISSUE THREAD

**Issue by JervenBolleman** [aws/graph-explorer#401]
## Description

A http GET request is easier to cache than a POST request. Considering the repeated nature of some of the queries this might give a big performance increase.

## Preferred Solution

If a request can be a GET use a GET instead of a POST (URL lenght < 700 chars).

## Additional Context

Caching POST requests is unusual and quite hard per https://www.rfc-editor.org/rfc/rfc7231

## Tasks

---

> [!IMPORTANT]
> If you are interested in working on this issue or have submitted
> a pull request, please leave a comment.

> [!TIP]
> Please use a 👍 reaction to provide a +1/vote.
>
> This helps the community and maintainers prioritize this request.

**Comment by kmcginnes** [comment]
💯% agree, that's why we are working on it 😄

Checkout #358 for the details.

- #358 

We are planning to use TanStack Query as a wrapper around the POST requests which will give us caching back at the client level.

**Comment by kmcginnes** [comment]
Closing to reduce confusion and focus on #358
