### ISSUE TITLE
[Bug] Unable to disable https using defined environment variables

### ISSUE THREAD

**Issue by triggan** [aws/graph-explorer#41]
When running graph-explorer within a container, I'm unable to disable https for the graph-explorer service using the following `docker run` command.  Https for the proxy does get disabled with this, but not the graph-explorer service (Vite server).

```
docker run -dit -p 5173:5173 -p 8182:8182 \
    --name <container_name> \
    --env GRAPH_EXP_HTTPS_CONNECTION=false \
    --env PROXY_SERVER_HTTPS_CONNECTION=false \
    -t <container_image>
```

**Comment by jackson-millard** [comment]
Those env variables aren't accepted inside the docker run command, you have to go into the .env file inside the graph-explorer folder and update them.

**Comment by michaelnchin** [comment]
A pending change in #108 will add support for specifying the value of `GRAPH_EXP_HTTPS_CONNECTION` via env variable.
