### ISSUE TITLE
Support for Non-String Vertex/Edge IDs with Property Graph Data

### ISSUE THREAD

**Issue by triggan** [aws/graph-explorer#55]
**Describe the bug**
At present, any use of non-String vertex IDs appears in the UI as `[object Object]`.  

![image](https://user-images.githubusercontent.com/8203156/220413039-9d8150d6-b7d5-4f40-a297-17a32c131023.png)

In the query response, the GraphSON response object contains the following:

```
...
{
    "@type":"g:Vertex",
    "@value":{
        "id":{
            "@type":"g:Int64",
            "@value":2306
        },
        "label":"airport"
   }
}
...
```

With using string-based IDs, the following is returned:

```
...
{
    "@type":"g:Vertex",
    "@value":{
        "id":"2306",
        "label":"airport"
   }
}
...
```

The extra `type` field gets returned for non-string IDs, causing the values to not be serialized properly back to the UI.

**To Reproduce**

Using Gremlin Server and TinkerGraph (with a `vertexIdManager=ANY`), create two vertices:

`g.addV('airport').property(id,'2306')`
and
`g.addV('airport').property(id,2306)`

**Expected behavior**
The ID should appear as the same value regardless of data type used.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 102.7.0esr

**Additional context**

**Comment by krlawrence** [comment]
Adding a note here that a Gremlin Server also allows for an ID to be a UUID. The PR #60 appears to handle integer IDs, but what about if the ID is a UUID? In the graph-explorer project we recently ran into this and had to make some changes for the UUID ID type.
