### ISSUE TITLE
[Feature Request] Editing node and edge properties.

### ISSUE THREAD

**Issue by ao97ngen** [aws/graph-explorer#621]
## Description

Hello,

I would like to propose a feature that enables the editing of node and edge properties in the Graph Explorer tool. While the tool currently offers robust functionalities for viewing the database, the lack of editing capabilities limits user interaction and data management. This enhancement would greatly benefit users who wish to contribute information without needing to rely on query languages.

Thank you!

## Preferred Solution

The "Details View" window should have editable fields.
Additionally, the functionality to add new properties should also be included, enhancing the flexibility and usability of the tool.

## Tasks

---

> [!IMPORTANT]
> If you are interested in working on this issue or have submitted
> a pull request, please leave a comment.

> [!TIP]
> Please use a 👍 reaction to provide a +1/vote.
>
> This helps the community and maintainers prioritize this request.

**Comment by kmcginnes** [comment]
Thanks for the feature request. Unfortunately, editing has been considered before and does not fit with the goals of the project.

- https://github.com/aws/graph-explorer/issues/66#issuecomment-2150800895

**Comment by kmcginnes** [comment]
FYI, this feature request is being tracked by the roadmap item:

- #693
