### ISSUE TITLE
[Feature request] Embeddability of components into custom applications

### ISSUE THREAD

**Issue by joywa** [aws/graph-explorer#65]
**Is your feature request related to a problem? Please describe.**
I want to embed the visualizations from Graph Explorer into my own custom built graph visualization application

**Describe the solution you'd like**
Provide an SDK or componentized version of Graph Explorer that can be added to any React-based project

**Describe alternatives you've considered**
Building my own visualizations

**Additional context**

**Comment by kmcginnes** [comment]
Unfortunately, this feature request does not align with the goals of Graph Explorer.

If you would like to create similar graph visualizations, there are many libraries available that provide those tools. The one Graph Explorer uses is [Cytoscape](https://cytoscape.org/).
