### ISSUE TITLE
[Feature request] Ability to write/update data from Explorer

### ISSUE THREAD

**Issue by joywa** [aws/graph-explorer#66]
**Is your feature request related to a problem? Please describe.**
I would like the ability to annotate data by adding new properties or edges or nodes and having the ability to overwrite an existing data point.

**Describe the solution you'd like**
Ability to perform CRUD operations on my data

**Describe alternatives you've considered**

**Additional context**

**Comment by qwaider** [comment]
- Add new Node
- Add new Edge
- Add properties to Edge/Node
- Edit Node properties
- Edit Edge properties
- Delete Node
- Delete Edge
- Delete properties of Edge/Node

**Comment by kmcginnes** [comment]
Unfortunately, the ability to write or update data does not fit with the core concept of Graph Explorer. Because of this, I am closing this feature request.

However, never say never. We may reconsider this decision in the future.

**Comment by kmcginnes** [comment]
FYI, this feature request is being tracked by the roadmap item:

- #693
