### ISSUE TITLE
[Bug] Local installation without SSL does not start

### ISSUE THREAD

**Issue by akuckartz** [aws/graph-explorer#87]
Graph Explorer can no longer be started without using SSL and certificates. The script https://github.com/aws/graph-explorer/blob/main/docker-entrypoint.sh then ends with `exit 1`. But according to https://github.com/aws/graph-explorer/blob/main/additionaldocs/development.md a docker container without GRAPH_EXP_HTTPS_CONNECTION should be accessible using http instead of https.

This results in significant additional efforts when AWS is to be installed and used only locally. And at the moment it is not clear if using SSL locally works. See https://github.com/aws/graph-explorer/discussions/86

**Comment by akuckartz** [comment]
This seems to be a duplicate of #41 which was already raised in January 2023.

**Comment by jackson-millard** [comment]
Currently, you can't provide the environment variables in charge of SSL via the docker run command. Those need to be set in the .env folder inside the graph-explorer folder.

**Comment by michaelnchin** [comment]
A pending change in #108 will add support for specifying the value of `GRAPH_EXP_HTTPS_CONNECTION` via env variable through `docker run`.
