### ISSUE TITLE
"No master credentials available"

### ISSUE THREAD

**Issue by akuckartz** [aws/graph-explorer#88]
### Discussed in https://github.com/aws/graph-explorer/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **akuckartz** April  1, 2023</sup>
I am trying to run AWS Graph Explorer locally.

What does this mean? Why is this happening?

```
Credentials undefined. Trying refresh.
No master credentials available Error: connect ECONNREFUSED 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  message: 'EC2 Metadata roleName request returned error',
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2023-04-01T18:52:07.484Z,
  originalError: {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80,
    message: 'connect ECONNREFUSED 169.254.169.254:80'
  }
}
```</div>

**Comment by akuckartz** [comment]
Same issue as discussed in #77 ?

**Comment by angelos-c** [comment]
@akuckartz did you manage to solve this? Facing the same problem

**Comment by akuckartz** [comment]
@angelos-c No, unfortunately not :-(

**Comment by triggan** [comment]
When you connect to graph explorer, are you using `https://localhost/explorer`?  The credentials error above is coming from the graph-explorer proxy service.  If you're not using IAM auth, then that can be ignored.

**Comment by akuckartz** [comment]
@triggan Thanks, but it is happening in combination with #87

**Comment by triggan** [comment]
Are you setting to `GRAPH_EXP_HTTPS_CONNECTION` to `false`, or just removing that parameter altogether?  I don't we account for the parameter being removed completely from the `.env` file.

**Comment by charlesivie** [comment]
Could you please clarify if you are using IAM, and are you setting `GRAPH_EXP_HTTPS_CONNECTION` to `false` as mentioned above? I am attempting to recreate your issue.

**Comment by charlesivie** [comment]
I am changing the logic around IAM checking of credentials, to avoid these messages being confusing in future.
