### ISSUE TITLE
[Bug] In data explorer view filter options show show Node Id and Node Type, Filters don't seem to do anything

### ISSUE THREAD

**Issue by abhishekpradeepmishra** [aws/graph-explorer#91]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
In data explorer view filter options show show Node Id and Node Type, Filters don't seem to do anything

 - OS: [e.g. Mac OS]
 - Browser: [e.g. Firefox]
 - Graph Explorer Version: [e.g. latest]
 - Graph Database & Version: [e.g., Amazon Neptune 1.2.0.2]

**To Reproduce**
1. Go to '.Graph Explorer'
2. Select Filters on top right
3. Nothing changes and no messages either. 

screenshot

![Screenshot 2023-04-13 at 9 40 24 AM](https://user-images.githubusercontent.com/67290492/231624889-b4d3dba0-1979-42f5-a45b-6449052bb50d.png)

**Expected behavior**
Filters should take effect and data should not be shown if nothing matches the filter or Appropriate error message should be shown

**Comment by kmcginnes** [comment]
Hi @abhishekpradeepmishra. Thank you for reporting this.

What you have come across here is a somewhat confusing bit of UI. It doesn't work the way you are expecting it to work.

The "Display Name" and "Display Description" drop downs are not filters. They are, in fact, defining what values will show in the table view within Graph Explorer.

You can see this in action if you follow these steps:

1. In the connections screen, open the "Data Explorer" for a specific node type

![CleanShot 2024-03-29 at 11 49 52@2x](https://github.com/aws/graph-explorer/assets/212862/287c0d17-a51f-4c9e-a383-613ac42ed72b)

2. Modify the Display Name and Display Description fields
3. Add a node to the explorer
4. Open the explorer

![CleanShot 2024-03-29 at 11 55 54@2x](https://github.com/aws/graph-explorer/assets/212862/00ad48b1-e653-4d73-8dce-9b36c87886c5)

5. Open the table view
6. See your selected display name and description in the table

![CleanShot 2024-03-29 at 11 51 51@2x](https://github.com/aws/graph-explorer/assets/212862/ef0f9855-51de-49a7-8f67-c9e702e47c37)

I hope this helps.

**Comment by xiazcy** [comment]
Closing this issue, please feel free to re-open if you have further questions.
